---
title: "Assignment 2 - Getting Started with R (20 pts)"
author: "FIRST NAME LAST NAME (UVA computing ID)"

output: html_document
---

**You will submit the html output.**

This assignment will use the popular Titanic dataset.Find the data dictionary for the dataset here: https://www.kaggle.com/competitions/titanic/data

```{r}
# Load the dataset; assign the dataframe to object called 'titanic'

titanic <- read.csv('../DS2003-Assignment 2/data/titanic.csv')

```

## Question 1 (.5 point)
```{r}
# Look at the first 6 rows of data

head(titanic)

```

## Question 2 (2 point)
```{r}
# (1) define the variable 'fare' (2) assign this column to vector called 'fare'& sort values from smallest to largest

# fare: price the passenger paid for their ticket

fare <- titanic$fare
order(fare)

```

## Question 3 (1 point)
```{r}
# subset the dataframe to include passengers in 2nd class and include the columns for name, age, and sex

titanic[titanic$pclass == 2, c('pclass', 'name', 'age', 'sex')]

```

## Question 4 (2 point)
```{r}
# How many NAs are in the full dataset? 

sum(is.na(titanic))

# How many NAs are in the 'age' column? (hint: you may need to Google)

sum(is.na(titanic$age))

```

## Question 5 (1 point)
```{r}
# Recode the variable 'sex' so that 'male' becomes 'm' and 'female' becomes 'f'

titanic <- transform(titanic, 
   sex = factor(sex, levels = c('male', 'female'), labels = c('m', 'f'))
)

```

## Question 6 (.5 point)
```{r}
# print summary statistics for the dataset

summary(titanic)

```

## Question 7 (1 point)
```{r}
# What is the average ticket price for a first class ticket?
# (optional: round to 2 decimal points)

round(mean(titanic$fare[titanic$pclass == 1]), 2)

```

## Question 8 (1 point)
```{r}
# Plot a histogram for the fare price using attach()

attach(titanic)

hist(fare)

detach(titanic)

```

## Question 9 (1 point)
```{r}
# Using lattice plot a histogram of fare price by port
library(lattice)
histogram(~ fare | embarked, data = titanic)
```


## Question 10 (1 point)
```{r}
# Write one sentence interpreting this graph

#There was a greater distribution of fares for people who embarked at Cherbourg compared to Southampton and Queenstown. 

```

## Question 11 (1 point)
```{r}
# Create a barplot of cabin class vs sex

barplot(table(titanic$pclass, titanic$sex))

```

## Question 12 (4 point)
```{r}
# (1) create a vector of 10 numbers which includes a few NAs (2) confirm it is a vector (3) sum the missing values (4) remove the missing values from your vector and then remove your vector object from the workspace

v <- c(3, NA, 55, 41, 22, NA, 88, 76, NA, 21)
is.vector(v)
sum(is.na(v))
na.omit(v)
rm(v)

```

## Question 13 (4 points)
```{r}
# (1) create a matrix of numbers from 1 to 500 going by 2's that is 25 rows by 10 columns (2) confirm it is a matrix (3) get the dimensions of the matrix (4) subset rows 10-15 and columns 3-6 (5)

m <- matrix(seq(from = 1, to = 500, by = 2), nrow = , ncol = 10)
is.matrix(m)
dim(m)
m[2:3, 3:4]
 

```







