---
title: "Assignment 2 - Getting Started with R (20 pts)"
author: "FIRST NAME LAST NAME (UVA computing ID)"

output: html_document
---

**You will submit the html output.**

This assignment will use the popular Titanic dataset.Find the data dictionary for the dataset here: https://www.kaggle.com/competitions/titanic/data

```{r}
# Load the dataset; assign the dataframe to object called 'titanic'

```

## Question 1 (0.5 point)
```{r}
# Look at the first 6 rows of data

```

## Question 2 (2 point)
```{r}
# (1) define the variable 'fare' (2) assign this column to vector called 'fare' & sort values from smallest to largest

# fare: 

```

## Question 3 (1 point)
```{r}
# subset the dataframe to include passengers in 2nd class and include the columns for name, age, and sex

```

## Question 4 (2 point)
```{r}
# How many NAs are in the full dataset? 

# How many NAs are in the 'age' column? (hint: you may need to Google)

```

## Question 5 (1 point)
```{r}
# Recode the variable 'sex' so that 'male' becomes 'm' and 'female' becomes 'f'

```

## Question 6 (.5 point)
```{r}
# print summary statistics for the dataset

```

## Question 7 (1 point)
```{r}
# What is the average ticket price for a first class ticket?
# (optional: round to 2 decimal points)

```

## Question 8 (1 point)
```{r}
# Plot a histogram for the fare price using attach()

```

## Question 9 (1 point)
```{r}
# Using lattice plot a histogram of fare price by port

```


## Question 10 (1 point)
```{r}
# Write one sentence interpreting the graph from Question  9

```

## Question 11 (1 point)
```{r}
# Create a barplot of cabin class vs sex

```

## Question 12 (4 point)
```{r}
# (1) create a vector of 10 numbers which includes a few NAs (2) confirm it is a vector (3) sum the missing values (4) remove the missing values from your vector and then remove your vector object from the workspace

```

## Question 13 (4 points)
```{r}
# (1) create a matrix of numbers from 1 to 500 going by 2's that is 25 rows by 10 columns (2) confirm it is a matrix (3) get the dimensions of the matrix (4) subset rows 10-15 and columns 3-6 (5)

```





