---
course: "DS2003: Communicating with Data"
class title: "Lab: ggplot2 -1 "
class number: "8"
---

```{r}
# import packages
library(tidyverse) #ggplot2 is part of the tidyverse
```


################################
# DATA
################################

```{r}
# Using mtcars dataset
str(mtcars)
```

###################################
# AESTHETIC MAPPING
###################################

```{r}
# Basic scatter plot with 1 geom
ggplot(mtcars,               #data source
       aes(x = wt,           # mapping wt to x
           y = mpg)) +       # mapping mpg to y
  geom_point()               # add geom layer
```

```{r}
# Basic scatter plot with 2 geoms
ggplot(mtcars,               
       aes(x = wt,           
           y = mpg)) +       
  geom_point() +
  geom_smooth()
```


# COLOR
```{r}

# When adding color in aesthetics mapping, it is tied to a variable
# Can be added in the base layer or geom layer

# base layer
ggplot(mtcars,               
       aes(x = wt,           
           y = mpg,
           color = cyl)) +       
  geom_point()  

# geom layer
ggplot(mtcars,               
       aes(x = wt,           
           y = mpg)) +       
  geom_point(aes(color = cyl)) 

# What looks wrong with this graph? (hint: look at the legend)
```
```{r}
# Convert cyl from numeric to factor
mtcars$fcyl <- as.factor(mtcars$cyl)
```

```{r}
ggplot(mtcars,               
       aes(x = wt,           
           y = mpg,
           color = fcyl)) +       
  geom_point() 
```

```{r}
# From lecture: When should we put aesthetics in base layer and when should we put them in the geom layer?
```

# SHAPES
```{r}
# The default shape for geom_point() is 19 (solid circle)
# All available shapes can be found using ?points

# Map fcyl to shape

ggplot(mtcars,               
       aes(x = wt,           
           y = mpg,
           shape = fcyl)) +       
  geom_point() 


# An is an exception where 'color' changes the inside color (vs the outline).

# Shape 21 is a solid circle that allows changes to its fill and color
```

# SHAPES, COLOR, FILL
```{r}
# Color refers to the outline of the shape.
ggplot(mtcars,               
       aes(x = wt,           
           y = mpg,
           color = fcyl)) +       
  geom_point(shape = 1) # note this is an attribute, will get to this soon
```

```{r}
# Fill refers to the inside color
ggplot(mtcars,               
       aes(x = wt,           
           y = mpg,
           fill = fcyl)) +       
  geom_point(shape = 24, size = 12) 
```

```{r}
# Some shapes allow color and fill
ggplot(mtcars,               
       aes(x = wt,           
           y = mpg,
           fill = fcyl)) +       
  geom_point(shape = 21, color  = 'white', size = 12) 
```

```{r}
# An exception is point markers. Instead of fill, use color to change the inside color
ggplot(mtcars,               
       aes(x = wt,           
           y = mpg,
           color = fcyl)) +       
  geom_point(size = 12) 
```

```{r}
# change shape and color by fcyl (although this is redundant information)
ggplot(mtcars,               
       aes(x = wt,           
           y = mpg,
           color = fcyl)) +       
  geom_point(aes(shape = fcyl)) 
```

#SIZE
```{r}
# with the aesthetics mappings so size is determined by variable (which is different from the size attribute seen above)
ggplot(mtcars,               
       aes(x = wt,           
           y = mpg,
           size = fcyl)) +       
  geom_point() 
```

#ALPHA (TRANSPARENCY)
```{r}
ggplot(mtcars,               
       aes(x = wt,           
           y = mpg,
           alpha = fcyl)) +       
  geom_point()
```

# LINETYPE
```{r}
ggplot(mtcars,               
       aes(x = wt,           
           y = mpg,
           linetype = fcyl)) +       
  geom_line()                   # Note change in geom layer
```

# LABELS
```{r}
ggplot(mtcars,               
       aes(x = wt,           
           y = mpg,
           label = fcyl)) +       
  geom_text()                 # Note change in geom layer
```

#########################################
# Mapping Attributes
#########################################

## Color & Fill
```{r}
ggplot(mtcars,               
       aes(x = wt,           
           y = mpg,
           color = fcyl)) +  # aesthetic     
  geom_point() +
  geom_smooth(color = 'pink', fill = 'white') # attribute
```

```{r}
# using HEX 

ggplot(mtcars,               
       aes(x = wt,           
           y = mpg,
           color = fcyl)) +  # aesthetic     
  geom_point() +
  geom_smooth(color = '#2A9D8F', fill = '#FFFFFF') # attribute
```


```{r}
# using HEX assigned to a variable

my_color1 = '#2A9D8F'
my_fill = '#FFFFFF'

ggplot(mtcars,               
       aes(x = wt,           
           y = mpg,
           color = fcyl)) +  # aesthetic     
  geom_point() +
  geom_smooth(color = my_color, fill = my_fill) # attribute
```
## SIZE
```{r}
ggplot(mtcars,               
       aes(x = wt,           
           y = mpg,
           color = fcyl)) +  # aesthetic     
  geom_point(size = 10) +  # attribute
  geom_smooth(color = my_color, fill = my_fill) # attribute
```

## ALPHA
```{r}
ggplot(mtcars,               
       aes(x = wt,           
           y = mpg,
           color = fcyl)) +  # aesthetic     
  geom_point(size = 10, alpha = 0.4) +  # attribute
  geom_smooth(color = my_color, fill = my_fill) # attribute
```

## LINETYPE
```{r}
ggplot(mtcars,               
       aes(x = wt,           
           y = mpg,
           color = fcyl)) +  # aesthetic     
  geom_point(size = 10, alpha = 0.4) +  # attribute
  geom_smooth(color = my_color, fill = my_fill, linetype = 'dashed') # attribute
```

# LABELS
```{r}
ggplot(mtcars,               
       aes(x = wt,           
           y = mpg,
           color = fcyl)) +  # aesthetic     
  geom_point(size = 10, alpha = 0.4) +  # attribute
  geom_smooth(color = my_color, fill = my_fill, linetype = 'dashed') +  # attribute
  geom_text(label = rownames(mtcars), size = 3) # attribute
``` 

```{r}
# labeling titles, y-axis, x-axis
ggplot(mtcars,               
       aes(x = wt,           
           y = mpg,
           color = fcyl)) +  # aesthetic     
  geom_point(size = 10, alpha = 0.4) +  # attribute
  geom_smooth(color = my_color, fill = my_fill, linetype = 'dashed') +  # attribute
  geom_text(label = rownames(mtcars), size = 3) + # attribute
  labs(
    title = 'MTCARS',
    subtitle = 'DS2003',
    caption = 'making charts is fun') +
  ylab('Miles per Gallon (MPG)') +
  xlab('Weight (Tons)')
    
  
```

```{r}
# labeling legend, using tag
ggplot(mtcars,               
       aes(x = wt,           
           y = mpg,
           color = fcyl)) +  # aesthetic     
  geom_point(size = 10, alpha = 0.4) +  # attribute
  geom_smooth(color = my_color, fill = my_fill, linetype = 'dashed') +  # attribute
  geom_text(label = rownames(mtcars), size = 3) + # attribute
  labs(
    title = 'MTCARS',
    subtitle = 'DS2003',
    caption = 'making charts is fun') +
  ylab('Miles per Gallon (MPG)') +
  xlab('Weight (Tons)') +
  labs(color = 'Cylinders', tag = 'A')

## to remove a label set it equal to NULL
```

## POSITION

```{r}
# position = 'identity' is default
ggplot(iris,     # new dataset               
       aes(x = Sepal.Length,           
           y = Sepal.Width,
           color = Species)) +       
  geom_point(position = 'identity') # in practice, don't need to specify default 

```

```{r}
# Jitter
ggplot(iris,     # new dataset               
       aes(x = Sepal.Length,           
           y = Sepal.Width,
           color = Species)) +       
  geom_point(position = 'jitter') 

# adds noise to x & y axis so all data points can be seen (no overlap)
```

```{r}
# All position arguments can also be used as functions. Helps with consistency across graphs

preset_jitter <- position_jitter (0.1, seed = 123) # how much noise

ggplot(iris,     # new dataset               
       aes(x = Sepal.Length,           
           y = Sepal.Width,
           color = Species)) +       
  geom_point(position = preset_jitter) 
```

```{r}
ggplot(iris,     # new dataset               
       aes(Sepal.Length,
           fill = Species)) +       
  geom_bar() 
```


```{r}
ggplot(iris,     # new dataset               
       aes(Sepal.Length,
           fill = Species)) +       
  geom_bar(position = 'dodge') 
```

```{r}
# others are position_jitterdodge(), position_nudge(), and position_stack()/position_fill()
```

## SCALES

```{r}
# Includes the labels scales seen above. 

# x-axis limits
ggplot(iris,                   
       aes(x = Sepal.Length,           
           y = Sepal.Width,
           color = Species)) +       
  geom_point(position = preset_jitter) + 
  xlim(5, 7)
```

```{r}
# Reverse axis
ggplot(iris,                   
       aes(x = Sepal.Length,           
           y = Sepal.Width,
           color = Species)) +       
  geom_point(position = preset_jitter) + 
  xlim(7, 5)
```

```{r}
# y-axis limits
ggplot(iris,                   
       aes(x = Sepal.Length,           
           y = Sepal.Width,
           color = Species)) +       
  geom_point(position = preset_jitter) + 
  ylim(2.5, 4)

# What are issues starting graphs not at zero?
```

```{r}
# color scales
ggplot(iris,                   
       aes(x = Sepal.Length,           
           y = Sepal.Width,
           color = Species)) +       
  geom_point(position = preset_jitter) + 
  scale_colour_brewer()

# so many color scales
```

################################
# GEOMETRIES
################################

```{r}
# Bar Graphs
# geom_bar()

ggplot(mtcars, aes(fcyl)) +
  geom_bar() # counts the number of cases at each x position
```

```{r}
# Calculate Descriptive Statistics
mtcars %>%
  select(fcyl, wt) %>%
  gather(key, value, -fcyl) %>%
  group_by(fcyl) %>%
  summarise(avg = mean(value),
            sd = sd(value)) -> mtcars_summary_long
```

```{r}
# Bar Graphs
# geom_col()
ggplot(mtcars_summary_long, aes(fcyl, avg)) +
  geom_col() + # plots actual values
  geom_errorbar(aes(ymin = avg - sd,
                    ymax = avg + sd),
                width = 0.1, 
                color = 'orange')
```

```{r}
#Bar Graph
# stat_count() - similar to geom_bar()
ggplot(mtcars, aes(fcyl)) +
  stat_count()
```

```{r}
#boxplot
ggplot(mtcars, aes(fcyl, mpg)) +
  geom_boxplot()
```

```{r}
# violin plot
ggplot(mtcars, aes(fcyl, mpg)) +
  geom_violin(scale = 'count', draw_quantiles = c(.25, .5, .75)) +
  geom_jitter(heigt = 0, width = 0.1)
```


```{r}
# density plots & reference lines
ggplot(mtcars, aes(mpg)) +
  geom_density() +
  geom_vline(xintercept = mean(mtcars$mpg))
```

```{r}
# dotplot
ggplot(mtcars, aes(mpg)) +
  geom_dotplot(binwidth = 1, aes(fill = fcyl)) +
  scale_color_hue()
```

```{r}
# geom layers from 2 different data sets
mtcars %>%
  group_by(fcyl) %>%
  summarise_all(mean) -> cars_summary
```

```{r}
ggplot(mtcars, aes(mpg, wt, color = fcyl)) +
  geom_point(shape = 1) +
  geom_point(data = cars_summary, size = 5)
  
```

##################################
# Facets
##################################

```{r}
ggplot(mtcars, aes(mpg, wt, color = hp)) +
  geom_point() +
  facet_wrap(vars(fcyl))
```

```{r}
ggplot(mtcars, aes(mpg, wt, color = hp)) +
  geom_point() +
  facet_grid(vars(fcyl), vars(gear))
```

##########################
# THEMES
##########################

```{r}
# Minimal
ggplot(mtcars, aes(mpg, wt, color = hp)) +
  geom_point() +
  theme_minimal()
```

```{r}
# Classic
ggplot(mtcars, aes(mpg, wt, color = hp)) +
  geom_point() +
  theme_classic()
```

```{r}
# Light

ggplot(mtcars, aes(mpg, wt, color = hp)) +
  geom_point() +
  theme_light()
```

```{r}
# There are a lot of themes built in to ggplot and plenty you can import
```

