---
course: 'DS2003: Communicating with Data'
class title: 'Introduction to R: Part 3'
class number: '4'
output: html_notebook
---

#LAB: DATAFRAMES in R
### You may work in groups of 2-3

```{r}
# Load the data 'income_exmpl.csv'

df <- read.csv('data/income_exmpl.csv')

```

```{r}
# Show the first 6 rows of the dataframe

head(df)
```

```{r}
# Select the first row

df[1, ]

```


```{r}
# select the first column

df[ , 1]
```


```{r}
# Select the first column by name

df[, 'sex']
```

```{r}
# Select the third row and the second column

df[3, 'age']

```

```{r}
# Select rows 5-25 row of the 'income' & 'age' column

df[5:25, c('age', 'income')]
```

```{r}
# sort the above output by smallest-largest age - keep data in a dataframe

df.1 <- df[5:25, c('age', 'income')]

position <- order(df.1$age)

df.1[position, ]
```
```{r}
# using the full dataset, subset the data for females at or over age 35 with low or med education 

subset(df, c(sex == 'f' & age >= 35 & edu == 'low' | edu == 'med.'))

```

```{r}
# determine amount of missing data in column 'age' - may need to Google

sum(is.na(df$age))

```

