---
course: "DS2003: Communicating with Data"
class title: "Lab: ggplot2 - 2 "
class number: "8"
---


```{r}
# install ggplot2

# load ggplot2
library(ggplot2)
```

```{r}
# explore the built in dataset 'diamonds'
str(diamonds)
```

```{r}
# look up information on the dataset 'diamonds'
?diamonds
```

```{r}
head(diamonds)
```


# Basic ggplot: gglot(dataset, aes(x, y)) + geom

################################
## PROBLEM SET #1: DIAMONDS
################################

```{r}
# Create a plot where x = carat, y = price and geometry = geom_point()

ggplot(diamonds, aes(carat, price)) + 
  geom_point()
```

```{r}
# Add a smooth geom to the plot

ggplot(diamonds, aes(carat, price)) + 
  geom_point() +
  geom_smooth()

```

```{r}
# Map the color aesthetic to clarity

ggplot(diamonds, aes(carat, price, color = clarity)) +
  geom_point() +
  geom_smooth()
```

```{r}
# Make the point 40% opaque by setting the alpha argument (inside geom_point) to 0.4. 
# Note this is an attribute vs an aesthetic. 
# Attributes are set in the geom layer and can overwrite your aesthetics

ggplot(diamonds, aes(carat, price, color = clarity)) +
  geom_point(alpha = 0.4) + 
  geom_smooth()
```

```{r}
# Create a scatter plot using the diamonds dataset, plot price vs carat
# Save this plot to plt_price_v_carat - saving plots can be useful when adding plots together

plt_price_v_carat <- ggplot(diamonds, aes(carat, price)) 

# add the point layer to plt_price_v_carat

plt_price_v_carat + geom_point()

```

```{r}
# map clarity to color inside of geom_point() and assign the plot to plt_price_vs_carat_by_clarity

plt_price_vs_carat_by_clarity <- plt_price_v_carat + geom_point(aes(color = clarity))
plt_price_vs_carat_by_clarity
```

################################
## PROBLEM SET #2: MTCARS
################################

```{r}
# Explore data set
str(mtcars)
```


```{r}
# Plot mpg vs weight in base layer. Save to variable plt

plt <- ggplot(mtcars, aes(mpg, wt))
```

```{r}
# Add point layer

plt + geom_point()
```
## Aesthetics
```{r}
# Map cylinder onto size

plt + geom_point(aes(size = cyl))
```

```{r}
# Look at the legend for cylinder. Does something seem off? How would you fix it? 
# Hint: what are the typical cylinders for a car?

mtcars$fcyl <- as.factor(mtcars$cyl)
```

```{r}
# Map cylinder onto size again

plt <- ggplot(mtcars, aes(mpg, wt))
plt + geom_point(aes(size = fcyl))
```

```{r}
# Map cylinder (as a factor) to alpha instead of size
plt + geom_point(aes(alpha = fcyl))
```

```{r}
# Map cylinder to shape
plt + geom_point(aes(shape = fcyl))
```

```{r}
# Map cylinder to label (hint: need to use different geom)
plt + geom_text(aes(label = fcyl))
```
## Attributes
```{r}
# set markers equal to specific color
# HEX codes are easy to use in R - pick a hex code and set it equal to  'color'
# Additionally set alpha to 0.75

plt + geom_point(color = "#2A9D8F", alpha = 0.75)

```

```{r}
# An different way to set a specific color to to have the color to a variable. 
# Save your color to the variable my_color and then use in your geom layer

my_color = "#2A9D8F"

plt + geom_point(color = my_color, alpha = 0.75)
```

```{r}
# add a shape equals 1 to the geom layer
plt + geom_point(shape = 1, color = my_color)
```

```{r}
# Map color to cylinder and add a geom_smooth layer in gray
plt + geom_point(shape = 1, aes(color = fcyl)) +
  geom_smooth(color = 'gray')
```


###################################
## PROBLEM SET #3: MTCARS
###################################

```{r}
# ggplot of x= wt, y = mpg, color = cylinder (as factor)
# geom_point with alpha = 0.5

ggplot(mtcars, aes(wt, mpg, color = fcyl)) +
  geom_point(alpha = 0.5)
```

```{r}
# Add text layer where label equals rownames in dark blue
ggplot(mtcars, aes(wt, mpg, color = fcyl)) +
  geom_point(alpha = 0.5) +
  geom_text(label = rownames(mtcars), color = "dark blue")
```

```{r}
# At the geom_point set shape equal to 24 and color = yellow
ggplot(mtcars, aes(wt, mpg, color = fcyl)) +
  geom_point(alpha = 0.5, shape = 24, color = 'yellow') +
  geom_text(label = rownames(mtcars), color = "dark blue")
```


```{r}

# Randomly select 50 observations from diamonds

# Set seed for reproducibility
set.seed(123)

# Random sample
d2 <- diamonds[sample(1:nrow(diamonds), 50), ]

```

```{r}
# Create a scatter plot of cut (factor) vs carat

ggplot(d2, aes(carat, cut)) +
  geom_point()
```

```{r}
# Switch the x and y axes

ggplot(d2, aes(cut, carat)) + 
  geom_point()
```

### What graph do you prefer?

```{r}
# Create a scatter plot of price vs carat and map cut to color

ggplot(d2, aes(carat, price, color = cut)) +
  geom_point()
```

```{r}
# look up the different shapes availability in ggplot2. Change the marker shape to an open circle. Also set the size of the marker to 1

?points()

ggplot(d2, aes(carat, price, color = cut)) +
  geom_point(shape = 1, size = 1)
```

### The default shape for geom_point() is 19 (solid circle). It is an exception where 'color' changes the inside color (vs the outline).

### Shape 21 is a solid cirlce that allows changes to its fill and color

```{r}
# Take the previous plot, change the shape to 21 and the transparency to 0.6 (60%)

ggplot(d2, aes(carat, price, fill = cut)) +
  geom_point(shape = 21, size = 1, alpha = 0.6)

```

```{r}
# in the ggplot() aesthetics map color to color

ggplot(d2, aes(carat, price, fill = cut, color = color)) +
  geom_point(shape = 21, size = 1, alpha = 0.6)
```

###############################################
## Plotting mtcars
###############################################

```{r}


```



