---
course: "DS2003: Communicating with Data"
class title: "Lab: ggplot2"
class number: "9"
---

```{r}
# import packages
library(tidyverse)
```


```{r}
# Read in income data
df <- read_csv('data.csv')
head(df)
```

```{r}
# summary of data
str(df)
```

```{r}
# Convert columns for 'occ' and 'edu' to be factors with levels (low, med, high)
df$occ <- factor(df$occ, levels = c('low', 'med', 'high'))
df$edu <- factor(df$edu, levels = c('low', 'med', 'high'))
```

```{r}
# change 'sex' variable factor with levels (male & female)
df$sex <- factor(df$sex, levels = c('m', 'f'), labels = c('male', 'female'))
```

## Barplots

```{r}
# create a bar plot that counts people with low, medium, and high occupation status respectively

ggplot(df, aes(occ)) + 
  geom_bar()
```

```{r}
# Add a title, color, and theme, differentiate by sex, and total count labels over the bars (don't be afraid to google)

ggplot(df, aes(occ)) +
  geom_bar(aes(fill = sex)) + 
  geom_text(stat = 'count', aes(label = ..count.. ), vjust = -1) +
  ylim(0, 720) +
  labs(
    title = 'Number of Participants by Occupational Status',
    xlab = 'Occupational Status', 
    ylab = 'Count') +
  scale_fill_brewer(palette= 'Dark2') +
  theme_minimal()

```

```{r}
# unstack the bars, which do you think is a better graph?
# use scale_fill_manual to set your colors

ggplot(df, aes(occ)) +
  geom_bar(aes(fill = sex), position = 'dodge') + 
  geom_text(stat = 'count', aes(label = ..count.. )) +
  ylim(0, 500) +
  labs(
    title = 'Number of Participants by Occupational Status',
    xlab = 'Occupational Status', 
    ylab = 'Count') +
  scale_fill_manual(values=c("#999999", "#E69F00"))
  theme_minimal()
```


```{r}
# Make the same graph with precomputed data (will need to consider changing default settings)

occ_counted <- df %>% count(occ, name = 'count') 
occ_counted

ggplot(occ_counted, aes(occ, count)) + 
  geom_bar(aes(fill = occ), stat = 'identity') +
  geom_text(aes(label = count ), vjust = -1) +
  ylim(0, 710) +
  labs(
    title = 'Number of Participants by Occupational Status',
    xlab = 'Occupational Status', 
    ylab = 'Count') +
  theme_minimal() 
```


```{r}
# look up the function after_stat()
# create the same bar graph using percents on the y axis (use data 'df')
# update the y axis label

ggplot(df, aes(occ, y = after_stat(100 * count/sum(count)))) + 
  geom_bar(aes(fill = sex)) +
  ylim(0, 100) +
  labs(
    title = 'Number of Participants by Occupational Status',
    xlab = 'Occupational Status', 
    ylab = 'Percent of Total') +
  theme_minimal() 
```


```{r}
# stacked plot with frequencies; used data occ_counted)
ggplot(occ_counted, aes(x = '', y = count, fill = occ)) + 
  geom_bar(stat = "identity")
```
```{r}
# Try to make this plot better by using position = 'fill'
# Change your labels appropiately

ggplot(occ_counted, aes(x = '', y = count, fill = occ)) + 
  geom_bar(stat = "identity", position = 'fill') +
  labs(
    title = 'Stacked Plot', 
    xlab = 'Occupation', 
    ylab = 'Proportion') +
  theme_minimal()
  
```

## Histogram

```{r}
# Draw a histogram with the variable income
ggplot(df, aes(income)) + 
  geom_histogram(bins = 20) + 
  theme_gray()
```

## Density Plot

```{r}
# plot a density plot of income

ggplot(df, aes(income)) + 
  geom_density() + 
  theme_minimal()
```

# Histogram with Density Plot

```{r}
# Graph the histogram and density plot together
ggplot(df, aes(x = income, y=..density..)) + 
  geom_histogram(bins=20, fill = 'white', color = 'gray') + 
  geom_density(aes(x = income), col="red") + 
  theme_minimal()
```

## Histogram with groups

```{r}
# Create a histogram separated by sex
ggplot(df, aes(income, fill = sex)) + 
  geom_histogram(bins=20, alpha=0.7) + 
  theme_bw()
```

## Boxplot

```{r}
# create a boxplot for income
ggplot(df, aes(x = income)) + 
  geom_boxplot() + 
  theme_bw()
```



```{r}
#Remove everything on the y-axis including the texts and tick marks

ggplot(df, aes(x = income)) + 
  geom_boxplot() + 
  theme_bw() +
  theme(axis.text.y=element_blank(),
        axis.ticks.y=element_blank())
```

```{r}
# Separate by sex
ggplot(df, aes(x = income, y = sex)) + 
  geom_boxplot() + 
  theme_bw()
```

## Violin Plot

```{r}
# Create a violin plot of income separated by sex
ggplot(df, aes(x = sex, y = income)) + 
  geom_violin() + 
  theme_bw()
```

```{r}
# overlay the data points and color by education

ggplot(df, aes(x = sex, y = income)) + 
  geom_violin() + 
  geom_jitter(width = 0.1, height = 0.1, alpha = 0.2, aes(color = edu)) + 
  theme_bw()
```
## Scatterplot

```{r}
# Create a scatterplot of income vs age
ggplot(df, aes(x = age, y = income)) + 
  geom_point() + 
  theme_bw()
```


```{r}
# It is hard to see the individual data points. Plot two ways to make it easy to see individual points

# with alpha
ggplot(df, aes(x = age, y = income)) + 
  geom_point(alpha=0.3) + 
  theme_bw()
```
```{r}
# with jitter
ggplot(df, aes(x = age, y = income)) + 
  geom_point() + 
  geom_jitter() +
  theme_bw()
```


```{r}
# show 2 ways to differentiate the points by sex

# by color
ggplot(df, aes(x = age, y = income, col=sex)) + 
  geom_point(alpha=0.3) + 
  theme_bw()
```
```{r}
# with shape
ggplot(df, aes(x = age, y = income, shape=sex)) + 
  geom_point(alpha=0.3) + 
  theme_bw()
```
## Facets

```{r}
# use faceting to separate scatter plot by sex
ggplot(df, aes(x = age, y = income)) + 
  geom_point(alpha = 0.3) + 
  facet_wrap(~ sex)
```

```{r}
# use faceting to separate by sex and edu using facet_wrap()
ggplot(df, aes(x = age, y = income)) + 
  geom_point(alpha = 0.3) + 
  facet_wrap(sex ~ edu)
```

```{r}
# use faceting to separate by sex and edu using facet_grid()
ggplot(df, aes(x = age, y = income)) + 
  geom_point(alpha = 0.3) + 
  facet_grid(sex ~ edu)
```
```{r}
# With extra time, go back through charts and practice changing colors, themes, labels, etc...
```

