---
title: "R Notebook"
output: html_notebook
---

## Vectors Creation
```{r}
# Below are vectors of basketball athletes and their total points and total rebounds during one game. 

athleteA <- c(15, 3)

athleteB <- c(20, 5)

athleteC <- c(10, 8)

athleteD <- c(12, 2)

```

## Question 1 (1 point)
```{r}
# Combine the 6 vectors into a single vector called 'stats'

stats <- c(athleteA, athleteB, athleteC, athleteD)
stats
```

## Question 2 (1 point)
```{r}
# construct a matrix where each athlete is a row. Call this matrix 'stat_matrix'

stats_matrix <- matrix(stats, nrow = 4, byrow = TRUE)
stats_matrix
```


## Question 3 (1 point)
```{r}
# Name the rows the respective fruits


rows <- c('athleteA', 'athleteB', 'athleteC', 'athleteD')

rownames(stats_matrix) <- rows
stats_matrix

```

## Question 4 (1 point)
```{r}
# Name the columns 'color' and 'taste'

columns <- c('points', 'rebounds')

colnames(stats_matrix) <- columns
stats_matrix
```

## Question 5 (2 points)
```{r}
# Create a 5th athlete and add their points and rebounds to the stats_matrix
athleteD <- c(15, 1)
name <- c('athleteD')

athleteD_matrix <- matrix(athleteD, 
                          nrow = 1, byrow = TRUE,
                           dimnames = list(name, columns))

team_matrix <- rbind(stats_matrix, athleteD_matrix)
team_matrix
```

## Question 6 (1 point)
```{r}
# Assuming only these 5 players played in the game, how many points and how many rebounds did the team make in the game?

colSums(stats_matrix)
```

## Question 7 (1 point)
```{r}
# Give an example of factor variable discussed in the introduction of "How Charts Lie"
# (no code)
```

## Question 8 (1 point)
```{r}
# Create a vector of factor variables "high", "med", and "low"
quality <- c("high", "med", "low")

fqualtiy <- as.factor(quality)
```

## Question 9 (1 point)
```{r}
# Rename factors to 'h', 'm', 'l'
levels(fquality) <- c('h', 'm', 'l')
fquality
```

## Question 10 (1 point)

```{r}

```

